# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=25)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('data_cadastro', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=30)),
                ('descricao', models.TextField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('data_cadastro', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=25)),
                ('data_vencimento', models.DateField(blank=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Estabelecimento')),
            ],
            options={
                'ordering': ('data_cadastro', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='TipoLancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=30)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('data_cadastro', 'nome'),
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='id_tipo_lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.TipoLancamento'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conta',
            name='id_estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Estabelecimento'),
        ),
    ]
