# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='usuario',
            field=models.ManyToManyField(related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
