# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20170825_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='id_estabelecimento',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='lancamento',
            old_name='id_estabelecimento',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='lancamento',
            old_name='id_tipo_lancamento',
            new_name='tipo_lancamento',
        ),
        migrations.RenameField(
            model_name='lancamento',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
